export type Shape = 'box' | 'sphere' | 'cylinder';
export type Category = 'tiny' | 'small' | 'medium' | 'large' | 'huge' | 'cosmic';

export interface CatalogObject {
  id: string;
  name: string;
  category: Category;
  dimensions: [number, number, number];
  volume: number;
  shape: Shape;
  icon: string;
  funFact: string;
  weight_kg: number;
  color: string;
}

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: 'tiny', label: 'Tiny' },
  { id: 'small', label: 'Small' },
  { id: 'medium', label: 'Medium' },
  { id: 'large', label: 'Large' },
  { id: 'huge', label: 'Huge' },
  { id: 'cosmic', label: 'Cosmic' },
];

const PI = Math.PI;
const sphereVol = (d: number) => (PI / 6) * d ** 3;
const cylVol = (d: number, h: number) => (PI / 4) * d ** 2 * h;

export const catalog: CatalogObject[] = [
  // ─── TINY ──────────────────────────────────────────
  {
    id: 'grain_of_sand',
    name: 'Grain of Sand',
    category: 'tiny',
    dimensions: [0.001, 0.001, 0.001],
    volume: sphereVol(0.001),
    shape: 'sphere',
    icon: '🏖️',
    funFact: 'More grains of sand on Earth than stars in the observable universe.',
    weight_kg: 0.0000067,
    color: '#e8d5a3',
  },
  {
    id: 'grain_of_rice',
    name: 'Grain of Rice',
    category: 'tiny',
    dimensions: [0.007, 0.002, 0.002],
    volume: 2.8e-8,
    shape: 'box',
    icon: '🍚',
    funFact: 'Over half the world\'s population relies on rice as a staple food.',
    weight_kg: 0.00003,
    color: '#f5f0e1',
  },
  {
    id: 'sesame_seed',
    name: 'Sesame Seed',
    category: 'tiny',
    dimensions: [0.003, 0.002, 0.001],
    volume: sphereVol(0.002),
    shape: 'sphere',
    icon: '🫘',
    funFact: 'Sesame is one of the oldest oilseed crops, domesticated over 3,000 years ago.',
    weight_kg: 0.000004,
    color: '#c4a862',
  },
  {
    id: 'ant',
    name: 'Ant',
    category: 'tiny',
    dimensions: [0.003, 0.001, 0.001],
    volume: 3e-9,
    shape: 'box',
    icon: '🐜',
    funFact: 'Ants can carry 10–50 times their own body weight.',
    weight_kg: 0.000001,
    color: '#2d1810',
  },
  {
    id: 'mm_candy',
    name: 'M&M',
    category: 'tiny',
    dimensions: [0.013, 0.009, 0.013],
    volume: sphereVol(0.013),
    shape: 'sphere',
    icon: '🍬',
    funFact: 'M&Ms were created in 1941 so soldiers could enjoy chocolate without it melting.',
    weight_kg: 0.0009,
    color: '#e53935',
  },
  {
    id: 'lego_brick',
    name: 'Lego Brick (2×4)',
    category: 'tiny',
    dimensions: [0.032, 0.012, 0.016],
    volume: 0.032 * 0.012 * 0.016,
    shape: 'box',
    icon: '🧱',
    funFact: 'There are about 80 Lego bricks per person on Earth.',
    weight_kg: 0.0023,
    color: '#f44336',
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    category: 'tiny',
    dimensions: [0.015, 0.012, 0.015],
    volume: sphereVol(0.014),
    shape: 'sphere',
    icon: '🫐',
    funFact: 'Blueberries are one of the only natural foods that are truly blue.',
    weight_kg: 0.0015,
    color: '#3949ab',
  },
  {
    id: 'postage_stamp',
    name: 'Postage Stamp',
    category: 'tiny',
    dimensions: [0.025, 0.0003, 0.021],
    volume: 0.025 * 0.0003 * 0.021,
    shape: 'box',
    icon: '📮',
    funFact: 'The first adhesive postage stamp, the Penny Black, was issued in 1840.',
    weight_kg: 0.001,
    color: '#1565c0',
  },
  {
    id: 'usb_c',
    name: 'USB-C Connector',
    category: 'tiny',
    dimensions: [0.009, 0.003, 0.007],
    volume: 0.009 * 0.003 * 0.007,
    shape: 'box',
    icon: '🔌',
    funFact: 'USB-C can deliver up to 240 watts of power.',
    weight_kg: 0.001,
    color: '#78909c',
  },
  {
    id: 'pill_capsule',
    name: 'Pill Capsule',
    category: 'tiny',
    dimensions: [0.007, 0.02, 0.007],
    volume: cylVol(0.007, 0.02),
    shape: 'cylinder',
    icon: '💊',
    funFact: 'The first gelatin capsule was patented in 1834.',
    weight_kg: 0.0005,
    color: '#ef5350',
  },
  {
    id: 'penny',
    name: 'Penny',
    category: 'tiny',
    dimensions: [0.019, 0.0015, 0.019],
    volume: cylVol(0.019, 0.0015),
    shape: 'cylinder',
    icon: '🪙',
    funFact: 'It costs about 2.7 cents to make a single penny.',
    weight_kg: 0.0025,
    color: '#bf6830',
  },
  {
    id: 'paperclip',
    name: 'Paperclip',
    category: 'tiny',
    dimensions: [0.033, 0.009, 0.001],
    volume: 2.97e-7,
    shape: 'box',
    icon: '📎',
    funFact: 'Norwegians wore paperclips on their lapels as a symbol of resistance during WWII.',
    weight_kg: 0.001,
    color: '#b0bec5',
  },
  {
    id: 'sd_card',
    name: 'SD Card',
    category: 'tiny',
    dimensions: [0.032, 0.002, 0.024],
    volume: 0.032 * 0.002 * 0.024,
    shape: 'box',
    icon: '💾',
    funFact: 'A 1TB SD card can hold about 250,000 photos.',
    weight_kg: 0.002,
    color: '#263238',
  },
  {
    id: 'cherry',
    name: 'Cherry',
    category: 'tiny',
    dimensions: [0.02, 0.02, 0.02],
    volume: sphereVol(0.02),
    shape: 'sphere',
    icon: '🍒',
    funFact: 'There are over 1,000 varieties of cherries in the United States alone.',
    weight_kg: 0.008,
    color: '#c62828',
  },

  // ─── SMALL ─────────────────────────────────────────
  {
    id: 'golf_ball',
    name: 'Golf Ball',
    category: 'small',
    dimensions: [0.043, 0.043, 0.043],
    volume: sphereVol(0.043),
    shape: 'sphere',
    icon: '⛳',
    funFact: 'A golf ball has 300–500 dimples that help it fly farther.',
    weight_kg: 0.046,
    color: '#fafafa',
  },
  {
    id: 'tennis_ball',
    name: 'Tennis Ball',
    category: 'small',
    dimensions: [0.067, 0.067, 0.067],
    volume: sphereVol(0.067),
    shape: 'sphere',
    icon: '🎾',
    funFact: 'Tennis balls are pressurized to about 12 psi inside.',
    weight_kg: 0.057,
    color: '#cddc39',
  },
  {
    id: 'rubiks_cube',
    name: "Rubik's Cube",
    category: 'small',
    dimensions: [0.057, 0.057, 0.057],
    volume: 0.057 ** 3,
    shape: 'box',
    icon: '🎲',
    funFact: 'There are 43 quintillion possible Rubik\'s Cube configurations.',
    weight_kg: 0.13,
    color: '#ff9800',
  },
  {
    id: 'iphone',
    name: 'iPhone',
    category: 'small',
    dimensions: [0.147, 0.008, 0.071],
    volume: 0.147 * 0.008 * 0.071,
    shape: 'box',
    icon: '📱',
    funFact: 'The first iPhone had only 128MB of RAM.',
    weight_kg: 0.174,
    color: '#37474f',
  },
  {
    id: 'baseball',
    name: 'Baseball',
    category: 'small',
    dimensions: [0.074, 0.074, 0.074],
    volume: sphereVol(0.074),
    shape: 'sphere',
    icon: '⚾',
    funFact: 'A baseball has exactly 108 double stitches.',
    weight_kg: 0.145,
    color: '#f5f5f0',
  },
  {
    id: 'coffee_mug',
    name: 'Coffee Mug',
    category: 'small',
    dimensions: [0.08, 0.095, 0.08],
    volume: cylVol(0.08, 0.095),
    shape: 'cylinder',
    icon: '☕',
    funFact: 'Over 2.25 billion cups of coffee are consumed worldwide every day.',
    weight_kg: 0.35,
    color: '#5d4037',
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'small',
    dimensions: [0.035, 0.20, 0.035],
    volume: cylVol(0.035, 0.20),
    shape: 'cylinder',
    icon: '🍌',
    funFact: 'Bananas are naturally slightly radioactive due to their potassium content.',
    weight_kg: 0.12,
    color: '#fdd835',
  },
  {
    id: 'soda_can',
    name: 'Can of Soda',
    category: 'small',
    dimensions: [0.066, 0.122, 0.066],
    volume: cylVol(0.066, 0.122),
    shape: 'cylinder',
    icon: '🥤',
    funFact: 'Americans consume about 12.4 billion gallons of soda per year.',
    weight_kg: 0.384,
    color: '#d32f2f',
  },
  {
    id: 'lightbulb',
    name: 'Lightbulb',
    category: 'small',
    dimensions: [0.06, 0.11, 0.06],
    volume: sphereVol(0.06),
    shape: 'sphere',
    icon: '💡',
    funFact: 'The longest-burning lightbulb has been on since 1901 in a California fire station.',
    weight_kg: 0.03,
    color: '#fff9c4',
  },
  {
    id: 'human_fist',
    name: 'Human Fist',
    category: 'small',
    dimensions: [0.10, 0.08, 0.07],
    volume: sphereVol(0.09),
    shape: 'sphere',
    icon: '✊',
    funFact: 'The human hand has 27 bones.',
    weight_kg: 0.4,
    color: '#e8b89d',
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'small',
    dimensions: [0.08, 0.075, 0.08],
    volume: sphereVol(0.08),
    shape: 'sphere',
    icon: '🍎',
    funFact: 'There are over 7,500 varieties of apples grown worldwide.',
    weight_kg: 0.2,
    color: '#c62828',
  },
  {
    id: 'billiard_ball',
    name: 'Billiard Ball',
    category: 'small',
    dimensions: [0.057, 0.057, 0.057],
    volume: sphereVol(0.057),
    shape: 'sphere',
    icon: '🎱',
    funFact: 'Billiard balls were once made from ivory.',
    weight_kg: 0.17,
    color: '#1a237e',
  },
  {
    id: 'computer_mouse',
    name: 'Computer Mouse',
    category: 'small',
    dimensions: [0.12, 0.04, 0.065],
    volume: 0.12 * 0.04 * 0.065,
    shape: 'box',
    icon: '🖱️',
    funFact: 'The first computer mouse was made of wood in 1964.',
    weight_kg: 0.1,
    color: '#212121',
  },
  {
    id: 'tv_remote',
    name: 'TV Remote',
    category: 'small',
    dimensions: [0.20, 0.025, 0.05],
    volume: 0.20 * 0.025 * 0.05,
    shape: 'box',
    icon: '📺',
    funFact: 'The average TV remote is pressed 500,000 times in its lifetime.',
    weight_kg: 0.12,
    color: '#424242',
  },

  // ─── MEDIUM ────────────────────────────────────────
  {
    id: 'basketball',
    name: 'Basketball',
    category: 'medium',
    dimensions: [0.24, 0.24, 0.24],
    volume: sphereVol(0.24),
    shape: 'sphere',
    icon: '🏀',
    funFact: 'The first basketball game used a soccer ball and peach baskets.',
    weight_kg: 0.62,
    color: '#e65100',
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'medium',
    dimensions: [0.30, 0.25, 0.30],
    volume: sphereVol(0.28),
    shape: 'sphere',
    icon: '🍉',
    funFact: 'Watermelons are 92% water.',
    weight_kg: 9,
    color: '#2e7d32',
  },
  {
    id: 'microwave',
    name: 'Microwave',
    category: 'medium',
    dimensions: [0.50, 0.30, 0.40],
    volume: 0.06,
    shape: 'box',
    icon: '📡',
    funFact: 'Microwaves were accidentally invented when a radar engineer\'s chocolate bar melted.',
    weight_kg: 13,
    color: '#546e7a',
  },
  {
    id: 'pc_tower',
    name: 'Desktop PC Tower',
    category: 'medium',
    dimensions: [0.20, 0.45, 0.45],
    volume: 0.0405,
    shape: 'box',
    icon: '🖥️',
    funFact: 'The first personal computer weighed 55 pounds.',
    weight_kg: 10,
    color: '#212121',
  },
  {
    id: 'car_tire',
    name: 'Car Tire',
    category: 'medium',
    dimensions: [0.65, 0.20, 0.65],
    volume: cylVol(0.65, 0.20),
    shape: 'cylinder',
    icon: '🛞',
    funFact: 'About 1 billion tires are produced globally each year.',
    weight_kg: 10,
    color: '#263238',
  },
  {
    id: 'suitcase',
    name: 'Suitcase',
    category: 'medium',
    dimensions: [0.70, 0.45, 0.25],
    volume: 0.07875,
    shape: 'box',
    icon: '🧳',
    funFact: 'Wheeled suitcases weren\'t invented until 1970.',
    weight_kg: 4,
    color: '#1565c0',
  },
  {
    id: 'guitar',
    name: 'Guitar',
    category: 'medium',
    dimensions: [0.37, 1.0, 0.12],
    volume: 0.0444,
    shape: 'box',
    icon: '🎸',
    funFact: 'The world\'s largest playable guitar is 13 meters long.',
    weight_kg: 2.5,
    color: '#6d4c41',
  },
  {
    id: 'office_chair',
    name: 'Office Chair',
    category: 'medium',
    dimensions: [0.65, 1.10, 0.65],
    volume: 0.46,
    shape: 'box',
    icon: '🪑',
    funFact: 'Charles Darwin is credited with adding wheels to his office chair.',
    weight_kg: 15,
    color: '#37474f',
  },
  {
    id: 'mini_fridge',
    name: 'Mini-Fridge',
    category: 'medium',
    dimensions: [0.50, 0.50, 0.45],
    volume: 0.1125,
    shape: 'box',
    icon: '🧊',
    funFact: 'Mini-fridges use about 100 kWh of electricity per year.',
    weight_kg: 20,
    color: '#e0e0e0',
  },
  {
    id: 'bathtub',
    name: 'Bathtub',
    category: 'medium',
    dimensions: [1.50, 0.55, 0.70],
    volume: 0.5775,
    shape: 'box',
    icon: '🛁',
    funFact: 'The average bathtub holds about 300 liters of water.',
    weight_kg: 80,
    color: '#eceff1',
  },
  {
    id: 'dishwasher',
    name: 'Dishwasher',
    category: 'medium',
    dimensions: [0.60, 0.85, 0.60],
    volume: 0.306,
    shape: 'box',
    icon: '🍽️',
    funFact: 'The first dishwasher was patented by Josephine Cochrane in 1886.',
    weight_kg: 50,
    color: '#90a4ae',
  },
  {
    id: 'vending_machine',
    name: 'Vending Machine',
    category: 'medium',
    dimensions: [0.90, 1.83, 0.80],
    volume: 1.32,
    shape: 'box',
    icon: '🏧',
    funFact: 'Japan has about 5 million vending machines — one for every 23 people.',
    weight_kg: 200,
    color: '#b71c1c',
  },
  {
    id: 'park_bench',
    name: 'Park Bench',
    category: 'medium',
    dimensions: [1.50, 0.80, 0.60],
    volume: 0.72,
    shape: 'box',
    icon: '🪑',
    funFact: 'Central Park has over 9,000 benches.',
    weight_kg: 60,
    color: '#4e342e',
  },

  // ─── LARGE ─────────────────────────────────────────
  {
    id: 'sedan',
    name: 'Car (Sedan)',
    category: 'large',
    dimensions: [4.5, 1.5, 1.8],
    volume: 8.0,
    shape: 'box',
    icon: '🚗',
    funFact: 'The average car has about 30,000 parts.',
    weight_kg: 1400,
    color: '#1565c0',
  },
  {
    id: 'grand_piano',
    name: 'Grand Piano',
    category: 'large',
    dimensions: [1.5, 1.0, 2.2],
    volume: 3.3,
    shape: 'box',
    icon: '🎹',
    funFact: 'A concert grand piano has about 12,000 individual parts.',
    weight_kg: 480,
    color: '#1a1a1a',
  },
  {
    id: 'elephant',
    name: 'African Elephant',
    category: 'large',
    dimensions: [3.5, 3.3, 6.0],
    volume: 5.5,
    shape: 'box',
    icon: '🐘',
    funFact: 'Elephants can\'t jump, but they can swim for up to 6 hours.',
    weight_kg: 5000,
    color: '#78909c',
  },
  {
    id: 'hot_tub',
    name: 'Hot Tub',
    category: 'large',
    dimensions: [2.1, 0.9, 2.1],
    volume: 1.6,
    shape: 'cylinder',
    icon: '♨️',
    funFact: 'The ancient Romans built public hot baths that could hold thousands.',
    weight_kg: 300,
    color: '#4fc3f7',
  },
  {
    id: 'shipping_container',
    name: 'Shipping Container (20ft)',
    category: 'large',
    dimensions: [6.06, 2.59, 2.44],
    volume: 33.2,
    shape: 'box',
    icon: '📦',
    funFact: 'About 97% of all shipping containers are made in China.',
    weight_kg: 2300,
    color: '#ff6f00',
  },
  {
    id: 'school_bus',
    name: 'School Bus',
    category: 'large',
    dimensions: [10.7, 2.7, 2.4],
    volume: 41.0,
    shape: 'box',
    icon: '🚌',
    funFact: 'About 480,000 school buses carry 26 million kids to school daily in the US.',
    weight_kg: 10000,
    color: '#ffc107',
  },
  {
    id: 't_rex',
    name: 'T-Rex',
    category: 'large',
    dimensions: [12.0, 3.7, 2.0],
    volume: 7.0,
    shape: 'box',
    icon: '🦖',
    funFact: 'T-Rex had a bite force of 12,800 pounds — enough to crush a car.',
    weight_kg: 7000,
    color: '#5d4037',
  },
  {
    id: 'blue_whale',
    name: 'Blue Whale',
    category: 'large',
    dimensions: [30.0, 5.0, 6.0],
    volume: 100,
    shape: 'cylinder',
    icon: '🐋',
    funFact: 'A blue whale\'s heart is the size of a small car.',
    weight_kg: 140000,
    color: '#1565c0',
  },
  {
    id: 'studio_apartment',
    name: 'Studio Apartment',
    category: 'large',
    dimensions: [6.3, 2.7, 6.3],
    volume: 107,
    shape: 'box',
    icon: '🏠',
    funFact: 'The average studio apartment in Manhattan costs over $2,800/month.',
    weight_kg: 0,
    color: '#8d6e63',
  },
  {
    id: 'basketball_court',
    name: 'Basketball Court',
    category: 'large',
    dimensions: [28.65, 7.0, 15.24],
    volume: 3056,
    shape: 'box',
    icon: '🏟️',
    funFact: 'An NBA basketball court is exactly 94 feet long.',
    weight_kg: 0,
    color: '#e65100',
  },
  {
    id: 'boeing_747',
    name: 'Boeing 747',
    category: 'large',
    dimensions: [70.7, 19.4, 64.4],
    volume: 876,
    shape: 'cylinder',
    icon: '✈️',
    funFact: 'A 747 has 6 million parts, and half of them are fasteners.',
    weight_kg: 178756,
    color: '#e0e0e0',
  },
  {
    id: 'fire_truck',
    name: 'Fire Truck',
    category: 'large',
    dimensions: [10.5, 3.2, 2.5],
    volume: 50,
    shape: 'box',
    icon: '🚒',
    funFact: 'Fire trucks carry between 500 and 3,000 gallons of water.',
    weight_kg: 19000,
    color: '#c62828',
  },
  {
    id: 'tiny_house',
    name: 'Tiny House',
    category: 'large',
    dimensions: [7.3, 3.7, 2.6],
    volume: 60,
    shape: 'box',
    icon: '🏡',
    funFact: 'The tiny house movement started in the US in the late 1990s.',
    weight_kg: 4500,
    color: '#795548',
  },

  // ─── HUGE ──────────────────────────────────────────
  {
    id: 'olympic_pool',
    name: 'Olympic Swimming Pool',
    category: 'huge',
    dimensions: [50, 2.0, 25],
    volume: 2500,
    shape: 'box',
    icon: '🏊',
    funFact: 'An Olympic pool holds 2.5 million liters (660,000 gallons) of water.',
    weight_kg: 2500000,
    color: '#0288d1',
  },
  {
    id: 'football_field',
    name: 'Football Field',
    category: 'huge',
    dimensions: [109.7, 10, 48.8],
    volume: 53534,
    shape: 'box',
    icon: '🏈',
    funFact: 'An NFL football field is exactly 100 yards long (plus two 10-yard end zones).',
    weight_kg: 0,
    color: '#2e7d32',
  },
  {
    id: 'statue_of_liberty',
    name: 'Statue of Liberty',
    category: 'huge',
    dimensions: [15, 93, 15],
    volume: 6540,
    shape: 'cylinder',
    icon: '🗽',
    funFact: 'Lady Liberty\'s nose is 4.5 feet long.',
    weight_kg: 204000,
    color: '#4db6ac',
  },
  {
    id: 'great_pyramid',
    name: 'Great Pyramid of Giza',
    category: 'huge',
    dimensions: [230, 146, 230],
    volume: 2583283,
    shape: 'box',
    icon: '🔺',
    funFact: 'The Great Pyramid was the tallest structure on Earth for 3,800 years.',
    weight_kg: 6e9,
    color: '#d4a843',
  },
  {
    id: 'titanic',
    name: 'Titanic',
    category: 'huge',
    dimensions: [269, 53, 28],
    volume: 131936,
    shape: 'box',
    icon: '🚢',
    funFact: 'The Titanic used 600 tons of coal per day.',
    weight_kg: 52000000,
    color: '#37474f',
  },
  {
    id: 'aircraft_carrier',
    name: 'Aircraft Carrier',
    category: 'huge',
    dimensions: [333, 77, 41],
    volume: 400000,
    shape: 'box',
    icon: '⚓',
    funFact: 'A Nimitz-class carrier carries enough food for 18,000 meals per day.',
    weight_kg: 100000000,
    color: '#455a64',
  },
  {
    id: 'iss',
    name: 'International Space Station',
    category: 'huge',
    dimensions: [108, 20, 73],
    volume: 916,
    shape: 'box',
    icon: '🛸',
    funFact: 'The ISS has been continuously inhabited since November 2000.',
    weight_kg: 420000,
    color: '#b0bec5',
  },
  {
    id: 'central_park',
    name: 'Central Park',
    category: 'huge',
    dimensions: [4000, 10, 800],
    volume: 32000000,
    shape: 'box',
    icon: '🌳',
    funFact: 'Central Park is visited by over 42 million people annually.',
    weight_kg: 0,
    color: '#388e3c',
  },
  {
    id: 'burj_khalifa',
    name: 'Burj Khalifa',
    category: 'huge',
    dimensions: [60, 828, 60],
    volume: 470000,
    shape: 'box',
    icon: '🏙️',
    funFact: 'The Burj Khalifa is so tall, you can watch two sunsets in one day from different floors.',
    weight_kg: 500000000,
    color: '#78909c',
  },
  {
    id: 'colosseum',
    name: 'Colosseum',
    category: 'huge',
    dimensions: [189, 48, 156],
    volume: 1300000,
    shape: 'cylinder',
    icon: '🏛️',
    funFact: 'The Colosseum could hold 50,000–80,000 spectators.',
    weight_kg: 0,
    color: '#a1887f',
  },
  {
    id: 'empire_state',
    name: 'Empire State Building',
    category: 'huge',
    dimensions: [57, 443, 129],
    volume: 1040000,
    shape: 'box',
    icon: '🏢',
    funFact: 'The Empire State Building has its own zip code: 10118.',
    weight_kg: 331000000,
    color: '#9e9e9e',
  },
  {
    id: 'walmart',
    name: 'Walmart Supercenter',
    category: 'huge',
    dimensions: [180, 7, 100],
    volume: 126000,
    shape: 'box',
    icon: '🛒',
    funFact: 'Walmart serves about 230 million customers per week.',
    weight_kg: 0,
    color: '#1565c0',
  },

  // ─── COSMIC ────────────────────────────────────────
  {
    id: 'moon',
    name: 'The Moon',
    category: 'cosmic',
    dimensions: [3474000, 3474000, 3474000],
    volume: 2.1958e19,
    shape: 'sphere',
    icon: '🌙',
    funFact: 'The Moon is slowly drifting away from Earth at 3.8 cm per year.',
    weight_kg: 7.35e22,
    color: '#bdbdbd',
  },
  {
    id: 'mars',
    name: 'Mars',
    category: 'cosmic',
    dimensions: [6779000, 6779000, 6779000],
    volume: 1.6318e20,
    shape: 'sphere',
    icon: '🔴',
    funFact: 'A day on Mars is only 37 minutes longer than a day on Earth.',
    weight_kg: 6.39e23,
    color: '#bf360c',
  },
  {
    id: 'earth',
    name: 'Earth',
    category: 'cosmic',
    dimensions: [12742000, 12742000, 12742000],
    volume: 1.08321e21,
    shape: 'sphere',
    icon: '🌍',
    funFact: 'Earth is the only planet not named after a Greek or Roman god.',
    weight_kg: 5.97e24,
    color: '#1565c0',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    category: 'cosmic',
    dimensions: [139820000, 139820000, 139820000],
    volume: 1.4313e24,
    shape: 'sphere',
    icon: '🟤',
    funFact: 'Jupiter\'s Great Red Spot is a storm bigger than Earth that has lasted 350+ years.',
    weight_kg: 1.898e27,
    color: '#bf6830',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    category: 'cosmic',
    dimensions: [116460000, 116460000, 116460000],
    volume: 8.2713e23,
    shape: 'sphere',
    icon: '🪐',
    funFact: 'Saturn is so light it would float in water (if you found a big enough bathtub).',
    weight_kg: 5.683e26,
    color: '#d4a843',
  },
  {
    id: 'sun',
    name: 'The Sun',
    category: 'cosmic',
    dimensions: [1392700000, 1392700000, 1392700000],
    volume: 1.412e27,
    shape: 'sphere',
    icon: '☀️',
    funFact: 'The Sun accounts for 99.86% of all mass in our solar system.',
    weight_kg: 1.989e30,
    color: '#ffab00',
  },
  {
    id: 'solar_system',
    name: 'Solar System',
    category: 'cosmic',
    dimensions: [9e12, 9e12, 9e12],
    volume: 3.81e38,
    shape: 'sphere',
    icon: '🌌',
    funFact: 'Light from the Sun takes about 4.5 hours to reach Neptune.',
    weight_kg: 2e30,
    color: '#311b92',
  },
  {
    id: 'light_year_cube',
    name: 'Light-Year Cube',
    category: 'cosmic',
    dimensions: [9.461e15, 9.461e15, 9.461e15],
    volume: 8.468e47,
    shape: 'box',
    icon: '✨',
    funFact: 'A light-year is about 9.46 trillion kilometers.',
    weight_kg: 0,
    color: '#e8eaf6',
  },
];

export function getById(id: string): CatalogObject | undefined {
  return catalog.find((o) => o.id === id);
}

export function getByCategory(cat: Category): CatalogObject[] {
  return catalog.filter((o) => o.category === cat);
}

export function searchCatalog(query: string): CatalogObject[] {
  const q = query.toLowerCase().trim();
  if (!q) return catalog;
  return catalog.filter(
    (o) =>
      o.name.toLowerCase().includes(q) ||
      o.category.includes(q) ||
      o.id.includes(q),
  );
}
