import type { WeaponDef, WeaponState } from './types';

export const WEAPON_DEFS: WeaponDef[] = [
  {
    name: 'PULSE RIFLE',
    slot: 0,
    icon: '⫏',
    damage: 18,
    headshotMultiplier: 2.5,
    fireRate: 10,
    magazineSize: 30,
    reserveAmmo: 150,
    reloadTime: 1.8,
    spread: 0.02,
    adsSpread: 0.005,
    recoilUp: 0.012,
    recoilSide: 0.004,
    range: 200,
    projectilesPerShot: 1,
    automatic: true,
    muzzleFlashScale: 1,
    screenShake: 0.3,
    type: 'hitscan',
  },
  {
    name: 'PLASMA SHOTGUN',
    slot: 1,
    icon: '⊞',
    damage: 12,
    headshotMultiplier: 1.5,
    fireRate: 1.5,
    magazineSize: 8,
    reserveAmmo: 32,
    reloadTime: 2.5,
    spread: 0.08,
    adsSpread: 0.05,
    recoilUp: 0.04,
    recoilSide: 0.015,
    range: 40,
    projectilesPerShot: 8,
    automatic: false,
    muzzleFlashScale: 2,
    screenShake: 0.8,
    type: 'hitscan',
  },
  {
    name: 'RAIL SNIPER',
    slot: 2,
    icon: '⊸',
    damage: 90,
    headshotMultiplier: 3,
    fireRate: 0.8,
    magazineSize: 5,
    reserveAmmo: 20,
    reloadTime: 3,
    spread: 0.001,
    adsSpread: 0,
    recoilUp: 0.06,
    recoilSide: 0.01,
    range: 500,
    projectilesPerShot: 1,
    automatic: false,
    muzzleFlashScale: 1.5,
    screenShake: 1.2,
    type: 'hitscan',
  },
  {
    name: 'HAVOC LAUNCHER',
    slot: 3,
    icon: '⊛',
    damage: 120,
    headshotMultiplier: 1,
    fireRate: 1.2,
    magazineSize: 4,
    reserveAmmo: 12,
    reloadTime: 3.5,
    spread: 0.01,
    adsSpread: 0.005,
    recoilUp: 0.05,
    recoilSide: 0.02,
    range: 300,
    projectilesPerShot: 1,
    automatic: false,
    muzzleFlashScale: 2.5,
    screenShake: 1.5,
    type: 'projectile',
    projectileSpeed: 60,
    explosionRadius: 6,
  },
];

export function createWeaponState(def: WeaponDef): WeaponState {
  return {
    def,
    currentAmmo: def.magazineSize,
    reserveAmmo: def.reserveAmmo,
    reloading: false,
    reloadTimer: 0,
    fireTimer: 0,
    equipped: false,
  };
}

export function createAllWeapons(): WeaponState[] {
  return WEAPON_DEFS.map((def) => createWeaponState(def));
}
