import type { WeaponDef, WeaponState } from './types';

export const WEAPON_DEFS: WeaponDef[] = [
  {
    name: 'PHANTOM AR',
    slot: 0,
    icon: '⫏',
    damage: 20,
    headshotMultiplier: 2.5,
    fireRate: 11,
    magazineSize: 32,
    reserveAmmo: 160,
    reloadTime: 1.6,
    spread: 0.018,
    adsSpread: 0.004,
    recoilUp: 0.011,
    recoilSide: 0.004,
    range: 200,
    projectilesPerShot: 1,
    automatic: true,
    muzzleFlashScale: 1,
    screenShake: 0.25,
    type: 'hitscan',
    altFireName: '3-ROUND BURST',
    altFireCooldown: 0.6,
    altFireType: 'burst',
  },
  {
    name: 'SCATTER GUN',
    slot: 1,
    icon: '⊞',
    damage: 14,
    headshotMultiplier: 1.5,
    fireRate: 1.8,
    magazineSize: 8,
    reserveAmmo: 40,
    reloadTime: 2.2,
    spread: 0.07,
    adsSpread: 0.04,
    recoilUp: 0.035,
    recoilSide: 0.012,
    range: 35,
    projectilesPerShot: 9,
    automatic: false,
    muzzleFlashScale: 2.2,
    screenShake: 0.7,
    type: 'hitscan',
    altFireName: 'INCENDIARY SLUG',
    altFireCooldown: 4,
    altFireType: 'explosive',
  },
  {
    name: 'VOLT SNIPER',
    slot: 2,
    icon: '⊸',
    damage: 95,
    headshotMultiplier: 3.5,
    fireRate: 0.9,
    magazineSize: 5,
    reserveAmmo: 25,
    reloadTime: 2.8,
    spread: 0.001,
    adsSpread: 0,
    recoilUp: 0.055,
    recoilSide: 0.008,
    range: 500,
    projectilesPerShot: 1,
    automatic: false,
    muzzleFlashScale: 1.5,
    screenShake: 1,
    type: 'hitscan',
    altFireName: 'CHARGED BEAM',
    altFireCooldown: 5,
    altFireType: 'beam',
  },
  {
    name: 'NOVA LAUNCHER',
    slot: 3,
    icon: '⊛',
    damage: 130,
    headshotMultiplier: 1,
    fireRate: 1.0,
    magazineSize: 4,
    reserveAmmo: 16,
    reloadTime: 3.2,
    spread: 0.008,
    adsSpread: 0.003,
    recoilUp: 0.05,
    recoilSide: 0.018,
    range: 300,
    projectilesPerShot: 1,
    automatic: false,
    muzzleFlashScale: 2.5,
    screenShake: 1.5,
    type: 'projectile',
    projectileSpeed: 65,
    explosionRadius: 7,
    altFireName: 'CLUSTER BOMB',
    altFireCooldown: 8,
    altFireType: 'explosive',
  },
  {
    name: 'ARC SMG',
    slot: 4,
    icon: '⊕',
    damage: 12,
    headshotMultiplier: 2,
    fireRate: 16,
    magazineSize: 45,
    reserveAmmo: 180,
    reloadTime: 1.8,
    spread: 0.03,
    adsSpread: 0.015,
    recoilUp: 0.008,
    recoilSide: 0.006,
    range: 120,
    projectilesPerShot: 1,
    automatic: true,
    muzzleFlashScale: 0.7,
    screenShake: 0.15,
    type: 'hitscan',
    altFireName: 'EMP PULSE',
    altFireCooldown: 6,
    altFireType: 'emp',
  },
];

export function createWeaponState(def: WeaponDef): WeaponState {
  return {
    def,
    currentAmmo: def.magazineSize,
    reserveAmmo: def.reserveAmmo,
    reloading: false,
    reloadTimer: 0,
    fireTimer: 0,
    equipped: false,
    altFireCooldownTimer: 0,
    altFireCharging: false,
    altFireChargeTime: 0,
  };
}

export function createAllWeapons(): WeaponState[] {
  return WEAPON_DEFS.map((def) => createWeaponState(def));
}
